services:
  - type: worker
    name: telegram-shayam-escrow-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
